// <auto-generated />
using System;
using AuthService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuthService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260824164810_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuthService.Infrastructure.Data.AuthAuditLogEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IpAddress")
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("LoginId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("login_id");

                    b.Property<string>("Reason")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("reason");

                    b.Property<string>("UserAgent")
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("user_agent");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_auth_audit_logs");

                    b.HasIndex("Action")
                        .HasDatabaseName("ix_auth_audit_logs_action");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_auth_audit_logs_created_at");

                    b.HasIndex("LoginId")
                        .HasDatabaseName("ix_auth_audit_logs_login_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_auth_audit_logs_user_id");

                    b.ToTable("auth_audit_logs", (string)null);
                });

            modelBuilder.Entity("AuthService.Infrastructure.Data.AuthTokenEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("issued_at");

                    b.Property<string>("LoginId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("login_id");

                    b.Property<string>("TokenJti")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("token_jti");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_auth_tokens");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_auth_tokens_expires_at");

                    b.HasIndex("IsRevoked")
                        .HasDatabaseName("ix_auth_tokens_is_revoked");

                    b.HasIndex("TokenJti")
                        .IsUnique()
                        .HasDatabaseName("ix_auth_tokens_token_jti");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_auth_tokens_user_id");

                    b.ToTable("auth_tokens", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
