// CONCEPT: ADO.NET (SqlConnection/SqlCommand/SqlParameter)
// Hand-written SQL audit-log writer that MIRRORS the behaviour of the EF Core AuditRepository.
// Selected when Settings.DataAccess == "AdoNet" (SQL Server only). Unlike the EF repo — which
// enqueues the entity on the shared DbContext and relies on the UnitOfWork to flush it — the
// ADO.NET path has no DbContext, so it persists the row immediately with a parameterised INSERT.
using System.Data;
using Microsoft.Data.SqlClient;
using UsersService.Config;
using UsersService.Domain.Models;
using UsersService.Mapping;

namespace UsersService.Infrastructure.Repositories;

public class AdoNetAuditRepository : IAuditRepository
{
    private readonly string _connectionString;
    private readonly ILogger<AdoNetAuditRepository> _logger;

    public AdoNetAuditRepository(Settings settings, ILogger<AdoNetAuditRepository> logger)
    {
        _connectionString = AdoNetUserRepository.BuildConnectionString(settings);
        _logger = logger;
    }

    public async Task<bool> LogActionAsync(AuditLog auditLog, CancellationToken ct = default)
    {
        try
        {
            // CONCEPT: raw SQL — parameterised INSERT into user_audit_logs. log_id is an IDENTITY
            // column, so it is omitted and generated by the DB. Reuse UserMapper.ToEntity so the
            // column values match the EF path exactly.
            var entity = UserMapper.ToEntity(auditLog);

            await using var connection = new SqlConnection(_connectionString);
            await connection.OpenAsync(ct);
            await using var command = new SqlCommand(
                @"INSERT INTO user_audit_logs (user_id, action, old_data, new_data, performed_by, timestamp)
                  VALUES (@user_id, @action, @old_data, @new_data, @performed_by, @timestamp)", connection);
            command.Parameters.Add(new SqlParameter("@user_id", SqlDbType.Int) { Value = (object?)entity.UserId ?? DBNull.Value });
            command.Parameters.Add(new SqlParameter("@action", SqlDbType.NVarChar, 30) { Value = entity.Action });
            command.Parameters.Add(new SqlParameter("@old_data", SqlDbType.NVarChar, -1) { Value = (object?)entity.OldData ?? DBNull.Value });
            command.Parameters.Add(new SqlParameter("@new_data", SqlDbType.NVarChar, -1) { Value = (object?)entity.NewData ?? DBNull.Value });
            command.Parameters.Add(new SqlParameter("@performed_by", SqlDbType.NVarChar, 50) { Value = (object?)entity.PerformedBy ?? DBNull.Value });
            command.Parameters.Add(new SqlParameter("@timestamp", SqlDbType.DateTime2) { Value = entity.Timestamp });

            await command.ExecuteNonQueryAsync(ct);
            _logger.LogInformation("Audit logged: {Action} for user_id {UserId}", auditLog.Action, auditLog.UserId?.Value);
            return true;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error logging audit action");
            return false;
        }
    }
}
