<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Moq" />
    <PackageReference Include="MSTest" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TransactionsService\TransactionsService.csproj" />
    <ProjectReference Include="..\shared\Gdb.Common\Gdb.Common.csproj" />
  </ItemGroup>

</Project>
