// <auto-generated />
using System;
using AccountsService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccountsService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260908122130_AddPerformanceIndexes")]
    partial class AddPerformanceIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccountsService.Infrastructure.Data.Entities.AccountEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountNumber")
                        .HasColumnType("integer")
                        .HasColumnName("account_number");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("account_type");

                    b.Property<DateTime>("ActivatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("activated_date");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("balance");

                    b.Property<string>("BankBranch")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("bank_branch");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("bank_name");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("closed_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IfscCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ifsc_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("pin_hash");

                    b.Property<string>("Privilege")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("privilege");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("row_version");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasAlternateKey("AccountNumber")
                        .HasName("ak_accounts_account_number");

                    b.HasIndex("AccountNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_account_number");

                    b.HasIndex("Privilege")
                        .HasDatabaseName("ix_accounts_privilege");

                    b.HasIndex("AccountType", "IsActive")
                        .HasDatabaseName("ix_accounts_type_active");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("AccountsService.Infrastructure.Data.Entities.CurrentAccountDetailsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountNumber")
                        .HasColumnType("integer")
                        .HasColumnName("account_number");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("company_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("RegistrationNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("registration_no");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_current_account_details");

                    b.HasIndex("AccountNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_current_account_details_account_number");

                    b.HasIndex("RegistrationNo")
                        .IsUnique()
                        .HasDatabaseName("ix_current_account_details_registration_no");

                    b.ToTable("current_account_details", (string)null);
                });

            modelBuilder.Entity("AccountsService.Infrastructure.Data.Entities.SavingsAccountDetailsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AadharHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("aadhar_hash");

                    b.Property<string>("AadharNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("aadhar_number");

                    b.Property<int>("AccountNumber")
                        .HasColumnType("integer")
                        .HasColumnName("account_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("gender");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_no");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_savings_account_details");

                    b.HasIndex("AadharHash")
                        .IsUnique()
                        .HasDatabaseName("ix_savings_account_details_aadhar_hash");

                    b.HasIndex("AccountNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_savings_account_details_account_number");

                    b.ToTable("savings_account_details", (string)null);
                });

            modelBuilder.Entity("AccountsService.Infrastructure.Data.Entities.CurrentAccountDetailsEntity", b =>
                {
                    b.HasOne("AccountsService.Infrastructure.Data.Entities.AccountEntity", "Account")
                        .WithOne("CurrentDetails")
                        .HasForeignKey("AccountsService.Infrastructure.Data.Entities.CurrentAccountDetailsEntity", "AccountNumber")
                        .HasPrincipalKey("AccountsService.Infrastructure.Data.Entities.AccountEntity", "AccountNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_current_account_details_accounts_account_number");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AccountsService.Infrastructure.Data.Entities.SavingsAccountDetailsEntity", b =>
                {
                    b.HasOne("AccountsService.Infrastructure.Data.Entities.AccountEntity", "Account")
                        .WithOne("SavingsDetails")
                        .HasForeignKey("AccountsService.Infrastructure.Data.Entities.SavingsAccountDetailsEntity", "AccountNumber")
                        .HasPrincipalKey("AccountsService.Infrastructure.Data.Entities.AccountEntity", "AccountNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_savings_account_details_accounts_account_number");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AccountsService.Infrastructure.Data.Entities.AccountEntity", b =>
                {
                    b.Navigation("CurrentDetails");

                    b.Navigation("SavingsDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
