// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TransactionsService.Infrastructure.Data;

#nullable disable

namespace TransactionsService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260908122140_AddPerformanceIndexes")]
    partial class AddPerformanceIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TransactionsService.Infrastructure.Data.FundTransferEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DestinationAccountId")
                        .HasColumnType("integer")
                        .HasColumnName("destination_account_id");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<int>("SourceAccountId")
                        .HasColumnType("integer")
                        .HasColumnName("source_account_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TransferMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transfer_mode");

                    b.HasKey("Id")
                        .HasName("pk_fund_transfers");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_fund_transfers_status_created");

                    b.HasIndex("SourceAccountId", "CreatedAt", "Status")
                        .HasDatabaseName("ix_fund_transfers_source_created_status");

                    b.ToTable("fund_transfers", (string)null);
                });

            modelBuilder.Entity("TransactionsService.Infrastructure.Data.IdempotencyKeyEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("response_body");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.HasKey("Key")
                        .HasName("pk_idempotency_keys");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_idempotency_keys_created_at");

                    b.ToTable("idempotency_keys", (string)null);
                });

            modelBuilder.Entity("TransactionsService.Infrastructure.Data.TransactionLogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("balance_after");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ReferenceId")
                        .HasColumnType("text")
                        .HasColumnName("reference_id");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transaction_type");

                    b.HasKey("Id")
                        .HasName("pk_transaction_logging");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_transaction_logging_account_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_transaction_logging_created_at");

                    b.HasIndex("AccountId", "CreatedAt")
                        .HasDatabaseName("ix_transaction_logging_account_created");

                    b.ToTable("transaction_logging", (string)null);
                });

            modelBuilder.Entity("TransactionsService.Infrastructure.Data.TransferLimitEntity", b =>
                {
                    b.Property<string>("Privilege")
                        .HasColumnType("text")
                        .HasColumnName("privilege");

                    b.Property<decimal>("DailyLimit")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("daily_limit");

                    b.Property<decimal>("PerTransactionLimit")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("per_transaction_limit");

                    b.HasKey("Privilege")
                        .HasName("pk_transfer_limits");

                    b.ToTable("transfer_limits", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
